@host = http://192.168.130.142:3000
@playerId = 74bbefcf-8e9c-43b2-b2c3-909473bfb4d9
@sharkId = 0000-000D
@arenaId = 8QY-4XY-YYYG


###

POST {{host}}/arena/create
Content-Type: application/json

{
    "arenaType": "private",
    "countdownToStart": 24,
    "gameLength": 43200,
    "players": [
        { "sharkName": "ryan" }
    ]
}

###

GET {{host}}/public-arenas 

###

GET {{host}}/arena/{{arenaId}}/settings
