@host = http://192.168.130.142:3000
@playerId = 514b4cc5-9382-46c6-b87c-a167fcbb8b43
@arenaId = ETY-JYY-YYY1

###

POST {{host}}/arena/create
Content-Type: application/json

{
    "arenaType": "private",
    "countdownToStart": 24,
    "gameLength": 43200,
    "players": [
        { "sharkName": "PATROL" }, 
        { "sharkName": "FP-TSHRK" }
    ]
}

###

GET {{host}}/public-arenas 

###

GET {{host}}/arena/{{arenaId}}/settings
