@host = http://192.168.130.142:3000
@playerId = 7e56febd-a3df-4680-8ff9-105136c52f19
@sharkId = 0000-000D
@arenaId = 1YY-5YY-YYYT

###

POST {{host}}/arena/create
Content-Type: application/json

{
    "arenaType": "private",
    "countdownToStart": 24,
    "gameLength": 43200,
    "players": [
        { "sharkName": "fp-tshrk" },
        { "sharkName": "patrol1" },
        { "sharkName": "patrol2" },
        { "sharkName": "patrol3" }
    ]
}

###

GET {{host}}/public-arenas 

###

GET {{host}}/arena/{{arenaId}}/settings
